### ISSUE TITLE
Unacast data

### ISSUE THREAD

**Issue by robpbrown** [Big-Bio/COVID19byZip#11]
Can we add this to the website somewhere?

Unacast Data

Unacast has created country-level social distancing metrics based on cell-phone locations. They currently have a score for changes in travel compared to a baseline (from early March) for total and non-essential travel. A letter grade is available from their website for each county, but we have applied for and received permission to you their full summary datasets. **We keep this dataset in a private repository. If you write to both us and to Unacast and show us proof that you have been granted access, we will link you to our private repo.** In our private repo we have the data formatted to match our other data sets and we have the time series of scores, not just the current values. You can read their methodology here: https://www.unacast.com/post/the-unacast-social-distancing-scoreboard

**Comment by jaquejbrito** [comment]
Just added to the main README.md. Any suggestions of names for sections?
We also updated StaticData READMe. Any feedback on them?

**Comment by robpbrown** [comment]
Let's change the name of the README in the static folder to be README_StaticData or something like that, just so we don't have any files with the same name

Otherwise they look good!

Are the new formatted data files up for static?

**Comment by jaquejbrito** [comment]
Changed the readme name.

**Comment by JRotman** [comment]
Yeah, all of the static data on the GitHub right now have been formatted according to the specs in the google doc, so the county/state/fips columns should work with the NYT data now.

**Comment by robpbrown** [comment]
sweet!!
