### ISSUE TITLE
AnalysisProject

### ISSUE THREAD

**Issue by robpbrown** [Big-Bio/COVID19byZip#13]
Lets create an AnalysisProject folder

I intend to put in the folder links to overleaf files where I am writing up and will post results from our analysis. Here is the link the first project I have written up. These are read only links, so people can see what we are working on as we get it done.

The below can be put in the README_AnalysisProjects file and we can keep this growing as we get more projects going.

This project uses static population covariate information along with daily metrics of social distancing based on cell phone location data to predict county and zip-code level specific COVID-19 case growth rates. 
https://www.overleaf.com/read/xkrywmmhysvh

**Comment by jaquejbrito** [comment]
Done.
