### ISSUE TITLE
Broken Links in README_StaticData.md

### ISSUE THREAD

**Issue by shaan97** [Big-Bio/COVID19byZip#20]
There are broken links in the README_StaticData.md file. For example the "ACS_Vehicle_Availability by *" links are all broken (and several more).

Since we have to fix these links anyway, I think it would be smart to use relative links for these references rather than absolute links (when I fork the repo, the links in my forked repo take me back to the original repository rather than my version of the file in my fork). 

Example fix:
`[ACS_Vehicle_Availability by Tract](tract_county_state/ACS_Vehicle_Availability_Variables_Centroids_byTract.csv)`

**Comment by jaquejbrito** [comment]
Changed to relative links.
