### ISSUE TITLE
case count data link

### ISSUE THREAD

**Issue by robpbrown** [Big-Bio/COVID19byZip#3]
Hi!

The static data is looking great! Today I'll work on getting the daily data in a useful format!

We should link to this somewhere appropriate: 

https://github.com/nytimes/covid-19-data

Here the nytimes is gathering all the state and county case counts and they keep it up to date. Most importantly, each country entry (or state entry) uses the corresponding FIPS code.

Thank you all for the hard work!

**Comment by jaquejbrito** [comment]
Added this link on the main README.
