### ISSUE TITLE
Static Data folders- create subfolders

### ISSUE THREAD

**Issue by robpbrown** [Big-Bio/COVID19byZip#4]
Hi, 

I'm thinking that inside the static data folder we should have some sub-folders

Since we will be training on country data but trying to predict into zip code or census tract data, we should have folders that give us data overlap information. For instance, if household income data is known in country, zip and tract levels it can be in a folder called country_zip_tract, but if age over 60+ is only known in county and tract levels, it can be in a folder called country_tract.

The reason I think that this is important is to that we don't train on covariates that will not be available for when trying to predict into smaller resolution areas.

The one thing to make sure of is that the format of the data is consistant between the different scales in each folder, we don't want income formatted different in the country data than in the tract data for instance. The variable headers and the way the data is encoded should be the same for example, (with obvious exceptions of FIPS for county and zip code for zip code.

Thoughts?

**Comment by jaquejbrito** [comment]
We have created subfolders according to the granularities we have now: country (there is one file containing a single line), tract_county_state, county_state and state. 
We can add more folders as new data is uploaded.

**Comment by jaquejbrito** [comment]
I think the organization is pretty set now.
